title: Your awesome title
author:
  name: Shakeel Hoosain
  email: shakeelhoosaincode@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  API Test JSON DATA

# Build settings

theme: minima

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #

  #   - { platform: github,         user_url: "https://github.com" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com" }
  #   - { platform: keybase,        user_url: "https://keybase.io" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com" }


# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
